const fs = require('node:fs');
const vm = require('node:vm');
const assert = require('node:assert/strict');
const decode = v => v.replace(/&gt;/g, '>').replace(/&lt;/g, '<').replace(/&amp;/g, '&').replace(/&quot;/g, '"');
const context = { console, crypto: require('node:crypto').webcrypto, URLSearchParams, document: { querySelector: () => null, createElement() { return { set innerHTML(value) { this.textContent = decode(value); this.children = [{ getAttribute: () => decode(value.match(/foo="([\s\S]*)"/)[1]) }]; } }; } } };
vm.createContext(context);
vm.runInContext(fs.readFileSync('orcaone/static/vendor/vue.global.prod.js', 'utf8'), context);
const lang = code => vm.runInNewContext(fs.readFileSync(`orcaone/static/texts/workbench-${code}.js`, 'utf8').replace('export default', 'result ='));
const DE = lang('de'), EN = lang('en');
assert.deepEqual(Object.keys(DE).sort(), Object.keys(EN).sort());
const calls = [];
Object.assign(context, { DE, EN, T: { locale: 'en' }, INSTANCES: [{ id: 'fixture', models: [{ model: 'actual', printers: ['A', 'B', 'C', 'D'].map(name => ({ name, nozzle_diameter: ['0.6'], processes: ['Quality'] })) }], processes: [{ name: 'Quality' }], filaments: [{ name: 'PLA', printers: { A: { status: 'visible' } } }] }], openProfileBranch: (...args) => calls.push(args), api: { async profileEditor(id, path, body) { calls.push({ id, path, body }); return path === '/composer-preview' ? { preview_id: 'preview', documents: [], issues: [], impacts: [{ kind: 'process', name: 'Other', key: 'inherits' }] } : { created: true, branch: { id: 'branch' } }; } } });
let source = fs.readFileSync('orcaone/static/pages/profile-workbench.js', 'utf8').replace(/^import .*;\r?\n/gm, '').replace(/export function /g, 'function ').replace('export default', 'globalThis.component =');
vm.runInContext(source, context);
const V = context.Vue;
V.compile(context.component.template, { onError(e) { throw e; } });
V.compile(context.component.components.WorkbenchTree.template, { onError(e) { throw e; } });
(async () => {
 const c = context.component, ui = c.setup({ instId: 'fixture' }, c.setup.length > 1 ? { emit() {} } : null);
 const root = ui.sources.value[0];
 // Use Vue's actual setup invocation contract, not only a manually supplied context.
 const renderer = V.createRenderer({ createComment: () => ({}), insert() {}, remove() {}, parentNode() {}, nextSibling() {} });
 const mounted = renderer.createApp({ setup: c.setup, props: c.props, render: () => null }, { instId: 'mounted-fixture' });
 mounted.mount({}); mounted.unmount();
 ui.selectSource(root, {}); await ui.addSelected();
 assert.equal(ui.draft.value.variants.length, 4);
 assert.equal(ui.draft.value.variants[0].nozzle_diameter[0], '0.6');
 assert.equal(ui.draft.value.assignments.length, 2, 'printer copies include process and filament assignments');
 const copiedProcess = ui.draft.value.assignments.find(a => a.kind === 'process');
 const copiedFilament = ui.draft.value.assignments.find(a => a.kind === 'filament');
 assert.equal(copiedProcess.action, 'copy');
 assert.equal(copiedProcess.targets.length, 4, 'shared process is copied once and assigned to all four target nozzles');
 assert.equal(copiedFilament.targets.length, 1, 'filament retains its precise nozzle scope');
 assert.equal(copiedFilament.targets[0], ui.draft.value.variants[0].key);
 assert.equal(ui.targets.value[0].children[0].children[0].children.length, 1, 'copied process appears in target tree');
 assert.equal(ui.targets.value[0].children[0].children[1].children.length, 1, 'copied filament appears in target tree');
 assert.ok(ui.targets.value[0].children.every(n => n.children.every(category => !ui.opened.value.includes(category.id))), 'inserted printer categories remain collapsed');
 const treeRender = V.compile(c.components.WorkbenchTree.template);
 const renderedTree = treeRender({ nodes: ui.targets.value[0].children[0].children, selected: [], opened: [], side: 'group', editing: '', W: EN, $emit() {} }, []);
 const renderedText = vnode => typeof vnode === 'string' ? vnode : Array.isArray(vnode) ? vnode.map(renderedText).join('') : vnode && typeof vnode === 'object' ? renderedText(vnode.children) : '';
 assert.ok(renderedText(renderedTree).includes(EN.processes + ' (1)'), 'process category renders its count');
 assert.ok(renderedText(renderedTree).includes(EN.filaments + ' (1)'), 'filament category renders its count');
 const listeners = new Map(); context.window = { addEventListener: (name, handler) => listeners.set(name, handler), removeEventListener: name => listeners.delete(name) };
 const guarded = renderer.createApp({ setup: c.setup, props: c.props, render: () => null }, { instId: 'fixture' }); guarded.mount({});
 let prevented = false; listeners.get('beforeunload')({ preventDefault() { prevented = true; } });
 assert.equal(prevented, true, 'browser unload warns while local draft exists');
 guarded.unmount(); assert.equal(listeners.size, 1, 'application unload guard survives page unmount');
 prevented = false; listeners.get('beforeunload')({ preventDefault() { prevented = true; } });
 assert.equal(prevented, true, 'draft retained on another page still warns on browser unload'); delete context.window;
 const machine = root.children[0], process = machine.children[0].children[0];
 ui.selectSource(process, {}); ui.mode.value = 'move'; await ui.addSelected();
 const movedProcess = ui.draft.value.assignments.find(a => a.action === 'move');
 assert.equal(movedProcess.from[0], 'A', 'drag origin controls move bindings');
 ui.selectSource(machine, {}); ui.selectSource(root.children[1], { ctrlKey: true });
 assert.equal(ui.sourceSelected.value.length, 2, 'Ctrl multi-selection');
 const transfer = { data: '', types: ['application/x-orcaone-workbench'], setData(_type, value) { this.data = value; }, getData() { return this.data; } };
 ui.selectSource(process, {}); ui.drag(process, { dataTransfer: transfer }, 'source');
 await ui.drop(ui.targets.value[0].children[1], { dataTransfer: transfer });
 assert.equal(movedProcess.targets.length, 2, 'drop retains exact source and adds selected target');
 const count = ui.draft.value.assignments.length;
 transfer.data = JSON.stringify({ token: 'foreign', instance: 'fixture', ids: [process.id] });
 await ui.drop(ui.targets.value[0].children[1], { dataTransfer: transfer });
 assert.equal(ui.draft.value.assignments.length, count, 'foreign drag rejected');
 ui.beginRename(ui.targets.value[0].children[0]); ui.renameText.value = 'Custom nozzle'; ui.commitRename();
 assert.equal(ui.draft.value.variants[0].name, 'Custom nozzle');
 ui.beginRename(ui.targets.value[0]); ui.renameText.value = 'Workshop'; ui.commitRename();
 assert.equal(ui.draft.value.target_model, 'Workshop');
 await ui.preview(); assert.equal(ui.review.value.impacts.length, 1);
 const previewBody = calls.at(-1).body;
 assert.equal(previewBody.assignments.filter(a => a.action === 'copy').length, 2, 'copied relationships reach backend preview');
 assert.ok(previewBody.assignments.every(a => a.targets.every(key => previewBody.variants.some(v => v.key === key))));
 ui.beginRename(ui.targets.value[0]); ui.renameText.value = 'Changed'; ui.commitRename(); await V.nextTick();
 assert.equal(ui.review.value, null, 'mutation invalidates preview');
 await ui.preview();
 await ui.createBranch(); assert.deepEqual(calls.at(-1), ['fixture', 'branch']);
 prevented = false; listeners.get('beforeunload')({ preventDefault() { prevented = true; } });
 assert.equal(prevented, false, 'cleared draft no longer warns');
 const moved = c.setup({ instId: 'fixture' }, { emit() {} });
 moved.mode.value = 'move'; moved.selectSource(moved.sources.value[0], {}); await moved.addSelected();
 const baseline = moved.targets.value[0].children[0].children[0].children[0];
 assert.equal(baseline.label, 'Quality', 'moved nozzle shows retained process relationship');
 assert.equal(baseline.baseline, true);
 assert.equal(moved.draft.value.assignments.length, 0, 'displaying retained relationships creates no API mutations');
 moved.beginRename(baseline); moved.renameText.value = 'Quality renamed'; moved.commitRename();
 assert.equal(moved.draft.value.assignments.length, 1, 'baseline rename stages an explicit assignment');
 assert.equal(moved.targets.value[0].children[0].children[0].children.length, 1, 'explicit relationship replaces baseline without duplication');
 const otherBaseline = moved.targets.value[0].children[1].children[0].children[0];
 moved.drag(otherBaseline, { dataTransfer: transfer }, 'target');
 await moved.drop(moved.targets.value[0].children[2], { dataTransfer: transfer });
 assert.equal(moved.draft.value.assignments.length, 1, 'baseline drag reuses existing identity assignment');
 assert.equal(moved.draft.value.assignments[0].action, 'move');
 assert.equal(moved.targets.value[0].children[1].children[0].children.length, 0, 'moved-away baseline disappears from old nozzle');
 const nozzleNode = moved.targets.value[0].children[0];
 assert.equal(nozzleNode.sizes[0], 0.6, 'nozzle icon uses actual diameter');
 moved.labelClick(nozzleNode, { timeStamp: 1000, detail: 1 }, 'target');
 assert.equal(moved.editing.value, '', 'first click only selects');
 moved.labelClick(nozzleNode, { timeStamp: 1100, detail: 2 }, 'target');
 assert.equal(moved.editing.value, '', 'native fast double click does not rename');
 moved.labelClick(nozzleNode, { timeStamp: 1700, detail: 1 }, 'target');
 assert.equal(moved.editing.value, nozzleNode.id, 'slow second title click renames'); moved.cancelRename();
 moved.labelClick(nozzleNode, { timeStamp: 2300, detail: 1, ctrlKey: true }, 'target');
 assert.equal(moved.editing.value, '', 'modifier click does not rename');
 moved.labelClick(nozzleNode, { timeStamp: 2900, detail: 1 }, 'target'); moved.toggle(nozzleNode.id);
 moved.labelClick(nozzleNode, { timeStamp: 3500, detail: 1 }, 'target');
 assert.equal(moved.editing.value, '', 'expander interaction cancels delayed rename');
 moved.selectTarget(moved.targets.value[0].children[0], {});
 const beforeDelete = moved.draft.value.variants.length;
 let deletePrevented = false;
 const deleteEvent = { target: { closest: () => true }, preventDefault() { deletePrevented = true; }, stopPropagation() {} };
 moved.deleteSelection(deleteEvent);
 assert.equal(moved.draft.value.variants.length, beforeDelete, 'Delete in text input preserves selection');
 deleteEvent.target.closest = () => null;
 moved.busy.value = true; moved.deleteSelection(deleteEvent);
 assert.equal(moved.draft.value.variants.length, beforeDelete, 'Delete while busy is ignored');
 moved.busy.value = false; moved.deleteSelection(deleteEvent);
 assert.equal(moved.draft.value.variants.length, beforeDelete - 1, 'Delete removes selected target variant');
 assert.equal(deletePrevented, true);
 assert.equal(moved.targetSelected.value.length, 0);
 assert.ok(moved.draft.value.assignments.every(a => a.targets.every(k => moved.draft.value.variants.some(v => v.key === k))), 'Delete cleans up target references');
 moved.reset();
 moved.mode.value = 'share'; moved.selectSource(moved.sources.value[0].children[0], {});
 await moved.newNozzle();
 assert.equal(moved.draft.value.assignments.length, 2, 'new nozzle includes source processes and filaments');
 assert.ok(moved.draft.value.assignments.every(a => a.action === 'copy'), 'new nozzle copies relationships regardless of toolbar mode');
 const originalRequest = context.api.profileEditor;
 context.api.profileEditor = async (_id, _path, body) => {
  if (!body.repair_compatibility) throw { code: 'profile_incomplete', data: { name: 'Legacy', repairable: true,
   issues: [{ code: 'invalid_type', key: 'z_hop_types', value: 'Normal Lift', expected: 'coEnums', origin: 'Parent' }] } };
  return { preview_id: 'repaired', issues: [], impacts: [] };
 };
 await moved.preview();
 assert.equal(moved.repairable.value, true, 'repair action offered only when server supports conversion');
 assert.ok(moved.error.value.includes('z_hop_types') && moved.error.value.includes('Parent'), 'error identifies field and origin');
 await moved.preview(true);
 assert.equal(moved.review.value.preview_id, 'repaired');
 assert.equal(moved.repairable.value, false);
 moved.review.value.repairs = [{ name: 'Legacy', kind: 'machine' }];
 const repairCalls = [];
 context.api.profileEditor = async (_id, path, body) => {
  repairCalls.push(path);
  assert.equal(body.repair_compatibility, true, 'rechecking retains accepted compatibility repair');
  return { preview_id: 'clean', repairs: [{ name: 'Legacy' }], issues: [] };
 };
 context.api.apply = async () => { throw new Error('Local repair must not write to slicer'); };
 await moved.applyRepair();
 assert.equal(moved.draft.value.repair_compatibility, true);
 assert.equal(moved.review.value.preview_id, 'repaired', 'validated preview remains available for merging');
 assert.equal(repairCalls.length, 0, 'local repair needs no write plan or slicer access');
 await moved.preview();
 assert.equal(moved.review.value.preview_id, 'clean');
 assert.equal(moved.draft.value.repair_compatibility, true);
 assert.deepEqual(repairCalls, ['/composer-preview']);
 context.api.profileEditor = originalRequest;
 moved.reset();
 const storage = new Map();
 context.window = { localStorage: { getItem: key => storage.get(key) || null, setItem: (key, value) => storage.set(key, value), removeItem: key => storage.delete(key) } };
 const saved = c.setup({ instId: 'fixture' }, { emit() {} });
 saved.selectSource(saved.sources.value[0], {}); await saved.addSelected();
 saved.draft.value.group_name = 'Remembered'; saved.draft.value.repair_compatibility = true;
 const previousKeys = saved.draft.value.variants.map(v => v.key);
 vm.runInContext('drafts.clear()', context);
 const resumed = c.setup({ instId: 'fixture' }, { emit() {} });
 assert.equal(resumed.draft.value.group_name, 'Remembered');
 assert.equal(resumed.draft.value.variants.length, 4);
 assert.equal(resumed.draft.value.assignments.length, 2);
 assert.equal(resumed.draft.value.repair_compatibility, true);
 resumed.selectSource(resumed.sources.value[0].children[0], {}); await resumed.newNozzle();
 assert.ok(!previousKeys.includes(resumed.draft.value.variants.at(-1).key), 'restored draft gets collision-free node IDs');
 resumed.reset(); assert.ok(!JSON.parse(storage.get('orcaone.workbench.v1.fixture') || '{}').variants?.length, 'discard removes persisted actions');
 delete context.window;
 const transferUi = c.setup({ instId: 'fixture' }, { emit() {} });
 transferUi.selectSource(transferUi.sources.value[0], {}); await transferUi.addSelected();
 const [sourceVariant, destinationVariant, thirdVariant] = transferUi.draft.value.variants;
 transferUi.selectTarget(transferUi.targets.value[0].children[0], {}); await V.nextTick();
 transferUi.removeVariantKeepProfiles();
 assert.equal(transferUi.draft.value.variants.length, 4, 'transfer requires an explicit valid destination');
 transferUi.transferTarget.value = sourceVariant.key; transferUi.removeVariantKeepProfiles();
 assert.equal(transferUi.draft.value.variants.length, 4, 'cannot transfer to self');
 transferUi.transferTarget.value = 'missing'; transferUi.removeVariantKeepProfiles();
 assert.equal(transferUi.draft.value.variants.length, 4, 'cannot transfer to absent variant');
 transferUi.transferTarget.value = destinationVariant.key; transferUi.removeVariantKeepProfiles();
 assert.equal(transferUi.draft.value.variants.length, 3);
 const sharedTransfer = transferUi.draft.value.assignments.find(a => a.kind === 'process');
 assert.equal(sharedTransfer.targets.length, 3, 'shared destination references deduplicated');
 assert.ok(sharedTransfer.targets.includes(thirdVariant.key), 'third variant membership retained');
 assert.equal(transferUi.draft.value.assignments.find(a => a.kind === 'filament').targets[0], destinationVariant.key, 'source-only filament retained');
 transferUi.reset(); transferUi.mode.value = 'move';
 transferUi.selectSource(transferUi.sources.value[0], {}); await transferUi.addSelected();
 const [baselineSource, baselineDestination] = transferUi.draft.value.variants;
 transferUi.selectTarget(transferUi.targets.value[0].children[0], {}); await V.nextTick();
 transferUi.transferTarget.value = baselineDestination.key; transferUi.removeVariantKeepProfiles();
 assert.equal(transferUi.draft.value.assignments.length, 2, 'implicit process and filament become explicit copies');
 assert.ok(transferUi.draft.value.assignments.every(a => a.action === 'copy' && a.targets.length === 1 && a.targets[0] === baselineDestination.key && a.from[0] === baselineSource.source_name));
 assert.ok(transferUi.targets.value[0].children[0].children.every(category => !transferUi.opened.value.includes(category.id)), 'transferred profile categories remain collapsed');
 context.api.profileEditor = async () => { throw { code: 'native_nozzle_conflict', data: { names: ['Conflict A', 'Conflict B'] } }; };
 await transferUi.preview();
 assert.ok(transferUi.error.value.includes('Conflict A') && transferUi.error.value.includes('Conflict B'));
 context.api.profileEditor = originalRequest; transferUi.reset();
 console.log('PASS: real Vue context, 4 sources, real nozzle metadata, explicit membership, move origin, inline rename, preview, branch handoff, Delete selection');
})().catch(error => { console.error(error); process.exitCode = 1; });
